http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  logger:
    host: localhost
    paths: ['']
  user:
    host: localhost
    paths: ['/user','/user/*']
  btcRate:
    host: localhost
    paths: ['/btcRate','/btcRate/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  loggerService:
    url: 'http://localhost:8083'
  userService:
    url: 'http://localhost:3000'
  btcRateService:
    url: 'http://localhost:8000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  loggerPipeline:
    apiEndpoints:
      - logger
    policies:
      - proxy:
          - action:
              serviceEndpoint: loggerService
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  btcRatePipeline:
    apiEndpoints:
      - btcRate
    policies:
      - proxy:
          - action:
              serviceEndpoint: btcRateService
              changeOrigin: true
